# Multiple hidden layers

<img src='images/MultipleHiddenLayers.png'>

In [48]:
a = np.arange(1,11).reshape(5,2)
b = np.arange(11,21).reshape(5,2)

In [49]:
print(a)
print(b)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]]


In [50]:
z = a * b
z

array([[ 11,  24],
       [ 39,  56],
       [ 75,  96],
       [119, 144],
       [171, 200]])

In [52]:
z=np.dot(a,b.T)
z

array([[ 35,  41,  47,  53,  59],
       [ 81,  95, 109, 123, 137],
       [127, 149, 171, 193, 215],
       [173, 203, 233, 263, 293],
       [219, 257, 295, 333, 371]])

In [42]:
q=np.random.randint(1,11,size=(3,2))
a=np.random.randint(11,21,size=(2,3))
a

array([[13, 15, 18],
       [11, 16, 18]])

In [43]:
q

array([[6, 8],
       [2, 7],
       [3, 9]])

In [44]:
np.dot(a,q)

array([[162, 371],
       [152, 362]])

TypeError: unsupported operand type(s) for *: 'int' and 'type'